version: '3.9'
services:
  mysql:
    build: src/main/resources/db
    container_name: mysql
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "127.0.0.1:${SERVER_PORT:-8080}:8080"

volumes:
  mysql_data: