apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: spotify-stats
  labels:
    app: spotify-stats
data:
  SERVER_PORT: "8080"
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: spotify
  SERVER_ADDRESS: 0.0.0.0
  SPOTIFY_SCOPES: user-read-recently-played,playlist-read-private
  SPOTIFY_REDIRECT_URI: https://your-domain.de/api/callback
